name: Compile OpenSSL For Android

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  OPENSSL_VERSION: 3.5.0
  WORK_PATH: /home/runner/work/openssl_for_android/openssl_for_android

jobs:
  Compile_OpenSSL_for_Android:
    name: Compile OpenSSL
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        info:
          - '{ "ANDROID_TARGET_ABI": "armeabi-v7a", "ANDROID_NDK": "r27c"}'
          - '{ "ANDROID_TARGET_ABI": "arm64-v8a", "ANDROID_NDK": "r27c"}'
          - '{ "ANDROID_TARGET_ABI": "riscv64", "ANDROID_NDK": "r27c"}'
          - '{ "ANDROID_TARGET_ABI": "x86", "ANDROID_NDK": "r27c"}'
          - '{ "ANDROID_TARGET_ABI": "x86_64", "ANDROID_NDK": "r27c"}'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Download Android NDK
        run: |
          aria2c -o android-ndk-${{fromJSON(matrix.info).ANDROID_NDK}}.zip https://dl.google.com/android/repository/android-ndk-${{fromJSON(matrix.info).ANDROID_NDK}}-linux.zip
          unzip android-ndk-${{fromJSON(matrix.info).ANDROID_NDK}}.zip

      - name: Download OpenSSL
        run: |
          aria2c -o openssl-${{env.OPENSSL_VERSION}}.tar.gz https://github.com/openssl/openssl/releases/download/openssl-${{env.OPENSSL_VERSION}}/openssl-${{env.OPENSSL_VERSION}}.tar.gz
          tar -zxvf openssl-${{env.OPENSSL_VERSION}}.tar.gz

      - name: Compile
        run: |
          bash ./openssl_build.sh ${{fromJSON(matrix.info).ANDROID_TARGET_ABI}} ${{env.OPENSSL_VERSION}} ${{fromJSON(matrix.info).ANDROID_NDK}}

      - name: Upload firmware
        uses: actions/upload-artifact@v4.6.2
        with:
          name: OpenSSL_${{env.OPENSSL_VERSION}}_${{fromJSON(matrix.info).ANDROID_TARGET_ABI}}.zip
          path: openssl_${{env.OPENSSL_VERSION}}_${{fromJSON(matrix.info).ANDROID_TARGET_ABI}}
          retention-days: 7
