name: Compile OpenSSL For Android

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  WORK_PATH: /home/runner/work/openssl_for_android/openssl_for_android

jobs:
  Compile_OpenSSL_for_Android:
    name: Compile OpenSSL
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - ANDROID_TARGET_ABI: arm64-v8a
          - ANDROID_TARGET_ABI: armeabi-v7a
          - ANDROID_TARGET_ABI: x86_64
          - ANDROID_TARGET_ABI: x86

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Get latest Android NDK version
        run: |
          tag_name=$(curl -s https://api.github.com/repos/android/ndk/releases/latest | jq -r .tag_name)
          echo "NDK_VERSION=$tag_name" >> $GITHUB_ENV

      - name: Download Android NDK
        run: |
          aria2c -o android-ndk-${{ env.NDK_VERSION }}.zip https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux.zip
          unzip android-ndk-${{ env.NDK_VERSION }}.zip

      - name: Get latest OpenSSL version
        run: |
          tag_name=$(curl -s https://api.github.com/repos/openssl/openssl/releases/latest | jq -r .tag_name)
          version=${tag_name#openssl-}
          echo "OPENSSL_VERSION=$version" >> $GITHUB_ENV

      - name: Download OpenSSL
        run: |
          aria2c -o openssl-${{ env.OPENSSL_VERSION }}.tar.gz https://github.com/openssl/openssl/releases/download/openssl-${{ env.OPENSSL_VERSION }}/openssl-${{ env.OPENSSL_VERSION }}.tar.gz
          tar -zxvf openssl-${{ env.OPENSSL_VERSION }}.tar.gz

      - name: Compile OpenSSL
        run: |
          bash ./openssl_build.sh ${{ matrix.ANDROID_TARGET_ABI }} ${{ env.OPENSSL_VERSION }} ${{ env.NDK_VERSION }}

      - name: Upload firmware
        uses: actions/upload-artifact@v4.6.2
        with:
          name: OpenSSL_${{ env.OPENSSL_VERSION }}_${{ matrix.ANDROID_TARGET_ABI }}.zip
          path: openssl_${{ env.OPENSSL_VERSION }}_${{ matrix.ANDROID_TARGET_ABI }}
          retention-days: 7
